/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import cyber.bank.gui.Event_View;
import cyber.bank.gui.Login_Frame;
import java.sql.DriverManager;
import java.sql.*;
import java.util.LinkedList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import manager.Manager;

/**
 *
 * @author User
 */
public class Manager_Main extends javax.swing.JFrame {
    Manager manager; 
    DefaultTableModel table;
    Connection conn =null;
    PreparedStatement pstmt =null;
    ResultSet rs = null;
    LinkedList<String> list = new LinkedList<String>();
    /**
     * Creates new form Manager_Main
     */
    public Manager_Main(Manager manager) {
        initComponents();
        this.manager=manager;
        NAME.setText(manager.getName());
        removeAll();
        MAIN_P.setVisible(true);
        createMain();
    }
    
    public void removeAll(){//패널 지우기
        MAIN_P.setVisible(false);
        EVENT_P.setVisible(false);
        LEVEL_BE_P.setVisible(false);
    }
    
    public void createMain(){ //메인 패널에 있는 보유 계좌 테이블 출력
        table = (DefaultTableModel) M_E_TABLE.getModel();
        table.setRowCount(0);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //접속 URL
            String jdbcDriver ="jdbc:mysql://118.67.129.235:3306/bank?serverTimezone=UTC"; 
            String dbUser ="banker"; //MySQL 접속 아이디
            String dbPass ="1234"; //비밀번호
            //Mysql bank 데이터베이스와 연결
            String sql = "select * from manager_news";
            conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPass);
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();
            table = (DefaultTableModel)M_E_TABLE.getModel();
            table.setNumRows(0);
            while(rs.next()){
                Object[] list = {rs.getString("date"),rs.getString("title"),rs.getString("writer")};
                table.addRow(list);//행추가
            }
            
        }catch(ClassNotFoundException | SQLException ex){
            System.out.println(ex.getMessage());
        }finally{
            if (rs !=null) try {rs.close();} catch (SQLException ex) {}
            if (pstmt !=null) try { pstmt.close(); } catch(SQLException ex) {}
            if (conn !=null) try { conn.close(); } catch(SQLException ex) {}
        }
    }
    
    public void gotoMain(){
        SLEVEL.setText(null);
        LEVEL.setSelectedIndex(0);
        ONE.setSelected(false);
        TWO.setSelected(false);
        THREE.setSelected(false);
        TITLE.setText(null);
        NEWS.setText(null);
        removeAll();
        MAIN_P.setVisible(true);
        createMain();
    }
    
    public void clearEvent(String level){
        showMessageDialog(null,level+" 혜택 설정이 완료되었습니다!");
        list.clear();
        gotoMain();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MAIN_P = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        M_E_TABLE = new javax.swing.JTable();
        TITLE_P = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MENU_P = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        INSERT = new javax.swing.JButton();
        CHANGE = new javax.swing.JButton();
        EVENT_P = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TITLE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NEWS = new javax.swing.JTextArea();
        insert_btn = new javax.swing.JButton();
        LEVEL_BE_P = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LEVEL = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        ONE = new javax.swing.JCheckBox();
        TWO = new javax.swing.JCheckBox();
        THREE = new javax.swing.JCheckBox();
        ACCEPT = new javax.swing.JButton();
        SLEVEL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        MAIN_P.setBackground(new java.awt.Color(255, 255, 255));
        MAIN_P.setPreferredSize(new java.awt.Dimension(550, 400));

        M_E_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일시", "제목", "작성자"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        M_E_TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_E_TABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(M_E_TABLE);

        javax.swing.GroupLayout MAIN_PLayout = new javax.swing.GroupLayout(MAIN_P);
        MAIN_P.setLayout(MAIN_PLayout);
        MAIN_PLayout.setHorizontalGroup(
            MAIN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        MAIN_PLayout.setVerticalGroup(
            MAIN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_PLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TITLE_P.setBackground(new java.awt.Color(204, 255, 204));
        TITLE_P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITLE_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TITLE_PMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("함초롬돋움", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MelonSoda Bank");

        javax.swing.GroupLayout TITLE_PLayout = new javax.swing.GroupLayout(TITLE_P);
        TITLE_P.setLayout(TITLE_PLayout);
        TITLE_PLayout.setHorizontalGroup(
            TITLE_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITLE_PLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TITLE_PLayout.setVerticalGroup(
            TITLE_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITLE_PLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        MENU_P.setBackground(new java.awt.Color(247, 247, 247));
        MENU_P.setPreferredSize(new java.awt.Dimension(150, 400));

        jLabel2.setText("님");

        NAME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NAME.setText("관리자");

        jLabel3.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel3.setText("메뉴");

        LOGOUT.setText("로그아웃");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        INSERT.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        INSERT.setText("공지사항 등록");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });

        CHANGE.setFont(new java.awt.Font("굴림", 0, 12)); // NOI18N
        CHANGE.setText("등급 혜택 변경");
        CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MENU_PLayout = new javax.swing.GroupLayout(MENU_P);
        MENU_P.setLayout(MENU_PLayout);
        MENU_PLayout.setHorizontalGroup(
            MENU_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENU_PLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(MENU_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(INSERT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHANGE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MENU_PLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );
        MENU_PLayout.setVerticalGroup(
            MENU_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENU_PLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MENU_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INSERT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHANGE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(LOGOUT)
                .addGap(29, 29, 29))
        );

        EVENT_P.setBackground(new java.awt.Color(255, 255, 255));
        EVENT_P.setPreferredSize(new java.awt.Dimension(550, 400));

        jLabel7.setText("제목");

        jLabel8.setText("내용");

        NEWS.setColumns(20);
        NEWS.setRows(5);
        jScrollPane3.setViewportView(NEWS);

        insert_btn.setText("등록하기");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EVENT_PLayout = new javax.swing.GroupLayout(EVENT_P);
        EVENT_P.setLayout(EVENT_PLayout);
        EVENT_PLayout.setHorizontalGroup(
            EVENT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EVENT_PLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(EVENT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane3)
                    .addComponent(insert_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        EVENT_PLayout.setVerticalGroup(
            EVENT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EVENT_PLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert_btn)
                .addGap(71, 71, 71))
        );

        LEVEL_BE_P.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 350));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true));

        jLabel4.setText("등급");

        LEVEL.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nomal", "Silver", "Gold", "Vip" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LEVEL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        LEVEL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LEVELValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(LEVEL);

        jLabel6.setText("혜택");

        ONE.setBackground(new java.awt.Color(204, 255, 204));
        ONE.setText("캐시백 5%");

        TWO.setBackground(new java.awt.Color(204, 255, 204));
        TWO.setText("melon 굿즈 증정");

        THREE.setBackground(new java.awt.Color(204, 255, 204));
        THREE.setText("연말 행사 초대권");

        ACCEPT.setText("등록하기");
        ACCEPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCEPTActionPerformed(evt);
            }
        });

        SLEVEL.setEditable(false);

        jLabel5.setText("선택 등급");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ONE)
                    .addComponent(TWO)
                    .addComponent(THREE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(SLEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACCEPT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SLEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ONE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TWO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(THREE)
                    .addComponent(ACCEPT))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LEVEL_BE_PLayout = new javax.swing.GroupLayout(LEVEL_BE_P);
        LEVEL_BE_P.setLayout(LEVEL_BE_PLayout);
        LEVEL_BE_PLayout.setHorizontalGroup(
            LEVEL_BE_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEVEL_BE_PLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        LEVEL_BE_PLayout.setVerticalGroup(
            LEVEL_BE_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LEVEL_BE_PLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MENU_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MAIN_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TITLE_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(EVENT_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(LEVEL_BE_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TITLE_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MENU_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAIN_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 100, Short.MAX_VALUE)
                    .addComponent(EVENT_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 100, Short.MAX_VALUE)
                    .addComponent(LEVEL_BE_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TITLE_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLE_PMouseClicked
        // TODO add your handling code here:
       gotoMain();
    }//GEN-LAST:event_TITLE_PMouseClicked

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        Login_Frame login = new Login_Frame();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void M_E_TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_E_TABLEMouseClicked
        // TODO add your handling code here:
        int row = M_E_TABLE.getSelectedRow();
        String key = (String) table.getValueAt(row, 1);
        Event_View v = new Event_View(key);
        v.setVisible(true);
    }//GEN-LAST:event_M_E_TABLEMouseClicked

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        // TODO add your handling code here:
        removeAll();
        EVENT_P.setVisible(true);
    }//GEN-LAST:event_INSERTActionPerformed

    private void CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEActionPerformed
        // TODO add your handling code here:
        removeAll();
        LEVEL_BE_P.setVisible(true);
    }//GEN-LAST:event_CHANGEActionPerformed

    private void ACCEPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCEPTActionPerformed
        // TODO add your handling code here:
        Level_Benefits b; //혜택 값을 받기위한 변수
        User_Level l; // 등급 값을 받기위한 변수
        if(!ONE.isSelected() && !TWO.isSelected() && !THREE.isSelected()){
            // 아무것도 추가하지 않았을 때 리스트에 " " 을 추가
            list.add(" ");
        }else{
            if(ONE.isSelected()){
                // 혜택 1번이 선택 되었을 때
                b = new CashBack();
                // 리스트에 혜택 1번 추가
                list.add((String) b.getBenefits());
            }
            if(TWO.isSelected()){
                // 혜택 2번이 선택되었을 때
                b = new Goods();
                // 리스트에 혜택 2번 추가
                list.add((String) b.getBenefits());
            }
            if(THREE.isSelected()){
                // 혜택 1번이 선택되었을 때
                b = new Invitation_Ticket();
                // 리스트에 혜택 3번 추가
                list.add((String) b.getBenefits());
            }
        }
        if(SLEVEL.getText().equals("Nomal")){
            // Nomal 등급이 선택되었을 때
            // 등급 생성자를 통해 혜택리스트 넘기기
            l = new Nomal(list);
            // DB에 저장하는 함수
            l.createLevel();
            clearEvent(SLEVEL.getText());
        }else if(SLEVEL.getText().equals("Silver")){
            // Silver 등급이 선택되었을 때
            // 등급 생성자를 통해 혜택리스트 넘기기
            l = new Silver(list);
            // DB에 저장하는 함수
            l.createLevel();
            clearEvent(SLEVEL.getText());
        }else if(SLEVEL.getText().equals("Gold")){
            // Gold 등급이 선택되었을 때
            // 등급 생성자를 통해 혜택리스트 넘기기
            l = new Gold(list);
            // DB에 저장하는 함수
            l.createLevel();
            clearEvent(SLEVEL.getText());
        }else if(SLEVEL.getText().equals("Vip")){
            // Vip 등급이 선택되었을 때
            // 등급 생성자를 통해 혜택리스트 넘기기
            l = new Vip(list);
            // DB에 저장하는 함수
            l.createLevel();
            clearEvent(SLEVEL.getText());
        }else{ // 등급 선택을 하지 않았을 시
            showMessageDialog(null,"등급이 선택되지 않았습니다.");
        }
    }//GEN-LAST:event_ACCEPTActionPerformed

    private void LEVELValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LEVELValueChanged
        // TODO add your handling code here:
        if(evt.getValueIsAdjusting()){ // 등급 선택시 선택된 등급을 보여준다
            SLEVEL.setText(LEVEL.getSelectedValue());
        }
    }//GEN-LAST:event_LEVELValueChanged

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
        Insert_Event e = new Insert_Event();
        Manager_Event m = new Manager_Event(e);
        User_Event u = new User_Event(e);
        e.addNews(TITLE.getText(),NEWS.getText(),manager.getName());
        showMessageDialog(null,"이벤트 등록이 완료되었습니다.");
        gotoMain();
    }//GEN-LAST:event_insert_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPT;
    private javax.swing.JButton CHANGE;
    private javax.swing.JPanel EVENT_P;
    private javax.swing.JButton INSERT;
    private javax.swing.JList<String> LEVEL;
    private javax.swing.JPanel LEVEL_BE_P;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JPanel MAIN_P;
    private javax.swing.JPanel MENU_P;
    private javax.swing.JTable M_E_TABLE;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextArea NEWS;
    private javax.swing.JCheckBox ONE;
    private javax.swing.JTextField SLEVEL;
    private javax.swing.JCheckBox THREE;
    private javax.swing.JTextField TITLE;
    private javax.swing.JPanel TITLE_P;
    private javax.swing.JCheckBox TWO;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
