/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cyber.bank;

import static cyber.bank.Manager_Main.goldList;
import static cyber.bank.Manager_Main.normalList;
import static cyber.bank.Manager_Main.silverList;
import static cyber.bank.Manager_Main.vipList;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

// 작성자 : 김부성
// 클래스 사용 이유 : 관리자가 등급별 공지사항을 선택 시 해당하는 등급의 공지사항을 출력한다.
// 옵저버 패턴의 결과를 등급 별로 확인할 수 있도록 제작

public class ShowLevelEvent extends javax.swing.JFrame {
    DefaultTableModel table;
    String level=null;
    LinkedList<Event> eList = new LinkedList<>(); // 출력할 등급의 리스트를 저장

    public ShowLevelEvent(String level) {
        initComponents();
        LEVEL.setText(level); //선택한 등급을 출력
        this.level=level;
        table = (DefaultTableModel) E_TABLE.getModel();
        createNews();
    }
    
    public void createNews(){ 
        //옵저버 패턴을 이용한 결과 공지사항 기능의 결과를 확인
        //등급별로 공지사항을 저장
        if(level.equals("Normal")){
            eList = normalList;
        }else if(level.equals("Silver")){
            eList = silverList;
        }else if(level.equals("Gold")){
            eList =  goldList;
        }else if(level.equals("Vip")){
            eList = vipList;
        }
        table.setNumRows(0);
        //등급에 해당하는 공지사항 출력
        for(int i=0; i<eList.size();i++){
                Object[] list = {eList.get(i).getDate(),eList.get(i).getTitle()};
                table.addRow(list);//행추가
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EXIT = new javax.swing.JButton();
        CHANGE = new javax.swing.JButton();
        LEVEL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        E_TABLE = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        EXIT.setText("닫기");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        CHANGE.setText("새로고침");
        CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEActionPerformed(evt);
            }
        });

        LEVEL.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        LEVEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        E_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "날짜", "제목"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        E_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        E_TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E_TABLEMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(E_TABLE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CHANGE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(LEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LEVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EXIT)
                    .addComponent(CHANGE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //새로고침
    private void CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEActionPerformed
        // TODO add your handling code here
       //등급별로 화면이 띄워져 있을 때 관리자가 새로운 공지사항을 등록 했을 때 새로고침하여 확인
        createNews();
    }//GEN-LAST:event_CHANGEActionPerformed
    
    //나가기 버튼
    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_EXITActionPerformed

    //공지사항 클릭시 본문 확인 가능
    private void E_TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E_TABLEMouseClicked
        // TODO add your handling code here:
        int row = E_TABLE.getSelectedRow();
        String key = (String) E_TABLE.getValueAt(row, 1);
        Event_View v = new Event_View(key);
        v.setVisible(true);
    }//GEN-LAST:event_E_TABLEMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHANGE;
    private javax.swing.JButton EXIT;
    private javax.swing.JTable E_TABLE;
    private javax.swing.JLabel LEVEL;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
